version: '3.5'
services:

  searchly_db:
    image: searchly_db
    container_name: searchly_db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - searchly
    ports:
      - 8089:5432

networks:
  searchly:
    name: searchly
    driver: bridge
